import { EmailMetadata } from '../types';
import { formatBytes } from './parser';

export const MOCK_EMAILS: EmailMetadata[] = [
  {
    id: 'mock-msg-001',
    threadId: 'mock-th-001',
    from: 'WeTransfer Support <noreply@wetransfer.com>',
    senderName: 'WeTransfer Support',
    senderEmail: 'noreply@wetransfer.com',
    senderDomain: 'wetransfer.com',
    to: 'user@example.com',
    subject: 'Files sent to you: Raw 4K Video Assets & Keynote (Expires in 7 days)',
    date: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    internalDate: Date.now() - 1000 * 60 * 60 * 4,
    ageDays: 0,
    sizeBytes: 24 * 1024 * 1024 + 480000, // 24.5 MB
    sizeFormatted: formatBytes(24 * 1024 * 1024 + 480000),
    isHeavy5MB: true,
    isHeavy10MB: true,
    isMassNotification: true,
    isAncient1Year: false,
    isAncient2Years: false,
    hasUnsubscribe: true,
    unsubscribeOptions: {
      httpUrl: 'https://wetransfer.com/unsubscribe?token=mock_wt_9921',
      hasOneClickPost: true,
      rawHeader: '<https://wetransfer.com/unsubscribe?token=mock_wt_9921>',
    },
    snippet: 'Hey Eyad, Sarah sent you files: "Brand_Video_Assets_Final.mov" (24.5MB). Click download before expiry.',
    labels: ['INBOX'],
  },
  {
    id: 'mock-msg-002',
    threadId: 'mock-th-002',
    from: 'Figma Updates <updates@figma.com>',
    senderName: 'Figma Updates',
    senderEmail: 'updates@figma.com',
    senderDomain: 'figma.com',
    to: 'user@example.com',
    subject: 'New Comments & Mentions in "Design System v3.2 Master"',
    date: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
    internalDate: Date.now() - 1000 * 60 * 60 * 22,
    ageDays: 1,
    sizeBytes: 12 * 1024 * 1024 + 200000, // 12.2 MB
    sizeFormatted: formatBytes(12 * 1024 * 1024 + 200000),
    isHeavy5MB: true,
    isHeavy10MB: true,
    isMassNotification: true,
    isAncient1Year: false,
    isAncient2Years: false,
    hasUnsubscribe: true,
    unsubscribeOptions: {
      httpUrl: 'https://figma.com/settings/notifications?unsub=email_weekly',
      hasOneClickPost: false,
      rawHeader: '<https://figma.com/settings/notifications?unsub=email_weekly>',
    },
    snippet: 'Alex left 6 new comments on Page 4 of your workspace. High-resolution vector exports preview attached.',
    labels: ['INBOX'],
  },
  {
    id: 'mock-msg-003',
    threadId: 'mock-th-003',
    from: 'GitHub Notifications <notifications@github.com>',
    senderName: 'GitHub Notifications',
    senderEmail: 'notifications@github.com',
    senderDomain: 'github.com',
    to: 'user@example.com',
    subject: '[acme/platform] Pull Request #142: Refactor auth middleware (merged)',
    date: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    internalDate: Date.now() - 1000 * 60 * 60 * 48,
    ageDays: 2,
    sizeBytes: 42000,
    sizeFormatted: formatBytes(42000),
    isHeavy5MB: false,
    isHeavy10MB: false,
    isMassNotification: true,
    isAncient1Year: false,
    isAncient2Years: false,
    hasUnsubscribe: true,
    unsubscribeOptions: {
      mailto: {
        address: 'unsubscribe@github.com',
        subject: 'Unsubscribe PR-142',
        body: 'Unsubscribe from thread notifications',
      },
      httpUrl: 'https://github.com/notifications/unsubscribe/acme_142',
      hasOneClickPost: true,
      rawHeader: '<mailto:unsubscribe@github.com?subject=Unsubscribe%20PR-142>, <https://github.com/notifications/unsubscribe/acme_142>',
    },
    snippet: 'Merged #142 into main. View the full diff on GitHub or review audit logs.',
    labels: ['INBOX'],
  },
  {
    id: 'mock-msg-004',
    threadId: 'mock-th-004',
    from: 'Substack Daily <digest@substack.com>',
    senderName: 'Substack Daily',
    senderEmail: 'digest@substack.com',
    senderDomain: 'substack.com',
    to: 'user@example.com',
    subject: 'The State of AI in 2026: Reasoning Models & Agentic Autonomy',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    internalDate: Date.now() - 1000 * 60 * 60 * 24 * 8,
    ageDays: 8,
    sizeBytes: 310000,
    sizeFormatted: formatBytes(310000),
    isHeavy5MB: false,
    isHeavy10MB: false,
    isMassNotification: true,
    isAncient1Year: false,
    isAncient2Years: false,
    hasUnsubscribe: true,
    unsubscribeOptions: {
      httpUrl: 'https://substack.com/unsubscribe/feed_token_8872',
      hasOneClickPost: true,
      rawHeader: '<https://substack.com/unsubscribe/feed_token_8872>',
    },
    snippet: 'Here is your weekly edition of Tech Dispatch. Deep dive into autonomous code generation paradigms.',
    labels: ['INBOX'],
  },
  {
    id: 'mock-msg-005',
    threadId: 'mock-th-005',
    from: 'LinkedIn Job Alerts <jobalerts-noreply@linkedin.com>',
    senderName: 'LinkedIn Job Alerts',
    senderEmail: 'jobalerts-noreply@linkedin.com',
    senderDomain: 'linkedin.com',
    to: 'user@example.com',
    subject: '30+ new Principal Software Engineer roles match your profile',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    internalDate: Date.now() - 1000 * 60 * 60 * 24 * 14,
    ageDays: 14,
    sizeBytes: 185000,
    sizeFormatted: formatBytes(185000),
    isHeavy5MB: false,
    isHeavy10MB: false,
    isMassNotification: true,
    isAncient1Year: false,
    isAncient2Years: false,
    hasUnsubscribe: true,
    unsubscribeOptions: {
      mailto: {
        address: 'unsubscribe@linkedin.com',
        subject: 'Unsubscribe Job Alerts',
      },
      httpUrl: 'https://www.linkedin.com/e/v2/unsub/jobalerts',
      hasOneClickPost: true,
      rawHeader: '<mailto:unsubscribe@linkedin.com?subject=Unsubscribe>, <https://www.linkedin.com/e/v2/unsub/jobalerts>',
    },
    snippet: 'Google, Anthropic, Stripe, and Apple are hiring leaders matching your skills.',
    labels: ['INBOX'],
  },
  {
    id: 'mock-msg-006',
    threadId: 'mock-th-006',
    from: 'Uber Receipts <uber.receipts@uber.com>',
    senderName: 'Uber Receipts',
    senderEmail: 'uber.receipts@uber.com',
    senderDomain: 'uber.com',
    to: 'user@example.com',
    subject: 'Your Friday morning trip with Uber ($34.82)',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 400).toISOString(), // > 1 year
    internalDate: Date.now() - 1000 * 60 * 60 * 24 * 400,
    ageDays: 400,
    sizeBytes: 94000,
    sizeFormatted: formatBytes(94000),
    isHeavy5MB: false,
    isHeavy10MB: false,
    isMassNotification: true,
    isAncient1Year: true,
    isAncient2Years: false,
    hasUnsubscribe: false,
    snippet: 'Total: $34.82. Payment method: Apple Pay (**** 4192). Download PDF tax invoice.',
    labels: ['INBOX'],
  },
  {
    id: 'mock-msg-007',
    threadId: 'mock-th-007',
    from: 'Old Cloud Backups <backup-daemon@acme-cloud.com>',
    senderName: 'Old Cloud Backups',
    senderEmail: 'backup-daemon@acme-cloud.com',
    senderDomain: 'acme-cloud.com',
    to: 'user@example.com',
    subject: 'Monthly Database Snapshot Archive 2024 (tar.gz)',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 820).toISOString(), // > 2 years
    internalDate: Date.now() - 1000 * 60 * 60 * 24 * 820,
    ageDays: 820,
    sizeBytes: 48 * 1024 * 1024, // 48 MB
    sizeFormatted: formatBytes(48 * 1024 * 1024),
    isHeavy5MB: true,
    isHeavy10MB: true,
    isMassNotification: true,
    isAncient1Year: true,
    isAncient2Years: true,
    hasUnsubscribe: false,
    snippet: 'Automated system snapshot completed. Full backup archive attached for cold storage.',
    labels: ['INBOX'],
  },
  {
    id: 'mock-msg-008',
    threadId: 'mock-th-008',
    from: 'Adobe Creative Cloud <creative-news@adobe.com>',
    senderName: 'Adobe Creative Cloud',
    senderEmail: 'creative-news@adobe.com',
    senderDomain: 'adobe.com',
    to: 'user@example.com',
    subject: 'Introducing Generative Fill v4 in Photoshop',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
    internalDate: Date.now() - 1000 * 60 * 60 * 24 * 45,
    ageDays: 45,
    sizeBytes: 6800000, // 6.8 MB
    sizeFormatted: formatBytes(6800000),
    isHeavy5MB: true,
    isHeavy10MB: false,
    isMassNotification: true,
    isAncient1Year: false,
    isAncient2Years: false,
    hasUnsubscribe: true,
    unsubscribeOptions: {
      httpUrl: 'https://adobe.com/preferences/unsubscribe?id=ad_99182',
      hasOneClickPost: true,
      rawHeader: '<https://adobe.com/preferences/unsubscribe?id=ad_99182>',
    },
    snippet: 'Discover next-generation AI image generation right inside Photoshop. Sample assets included.',
    labels: ['INBOX'],
  },
  {
    id: 'mock-msg-009',
    threadId: 'mock-th-009',
    from: 'Canva Digest <news@canva.com>',
    senderName: 'Canva Digest',
    senderEmail: 'news@canva.com',
    senderDomain: 'canva.com',
    to: 'user@example.com',
    subject: 'Your Weekly Design Inspiration: 50+ New Templates',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    internalDate: Date.now() - 1000 * 60 * 60 * 24 * 60,
    ageDays: 60,
    sizeBytes: 850000,
    sizeFormatted: formatBytes(850000),
    isHeavy5MB: false,
    isHeavy10MB: false,
    isMassNotification: true,
    isAncient1Year: false,
    isAncient2Years: false,
    hasUnsubscribe: true,
    unsubscribeOptions: {
      httpUrl: 'https://canva.com/unsubscribe?user_token=cnv_391',
      hasOneClickPost: true,
      rawHeader: '<https://canva.com/unsubscribe?user_token=cnv_391>',
    },
    snippet: 'Check out trending presentation slides, social media kits, and brand templates.',
    labels: ['INBOX'],
  },
  {
    id: 'mock-msg-010',
    threadId: 'mock-th-010',
    from: 'Spotify Weekly <discover@spotify.com>',
    senderName: 'Spotify Weekly',
    senderEmail: 'discover@spotify.com',
    senderDomain: 'spotify.com',
    to: 'user@example.com',
    subject: 'Your Discover Weekly is ready with 30 tracks you might love',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
    internalDate: Date.now() - 1000 * 60 * 60 * 24 * 90,
    ageDays: 90,
    sizeBytes: 120000,
    sizeFormatted: formatBytes(120000),
    isHeavy5MB: false,
    isHeavy10MB: false,
    isMassNotification: true,
    isAncient1Year: false,
    isAncient2Years: false,
    hasUnsubscribe: true,
    unsubscribeOptions: {
      httpUrl: 'https://spotify.com/account/unsubscribe?code=spt_883',
      hasOneClickPost: false,
      rawHeader: '<https://spotify.com/account/unsubscribe?code=spt_883>',
    },
    snippet: 'Updated every Monday. New tracks from Tycho, Bonobo, and Lane 8 customized to your listening style.',
    labels: ['INBOX'],
  },
  {
    id: 'mock-msg-011',
    threadId: 'mock-th-011',
    from: 'Promotions Daily <sales@spamdaily.com>',
    senderName: 'Promotions Daily',
    senderEmail: 'sales@spamdaily.com',
    senderDomain: 'spamdaily.com',
    to: 'user@example.com',
    subject: 'URGENT: 90% OFF Lifetime Access ends in 2 hours!',
    date: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    internalDate: Date.now() - 1000 * 60 * 60 * 12,
    ageDays: 0,
    sizeBytes: 65000,
    sizeFormatted: formatBytes(65000),
    isHeavy5MB: false,
    isHeavy10MB: false,
    isMassNotification: true,
    isAncient1Year: false,
    isAncient2Years: false,
    hasUnsubscribe: false, // Intentionally missing unsubscribe header to demonstrate Block Sender fallback!
    snippet: 'Do not miss our biggest clearance sale ever! Discount automatically applied at checkout.',
    labels: ['INBOX'],
  },
  {
    id: 'mock-msg-012',
    threadId: 'mock-th-012',
    from: 'Coursera Learning <learning@coursera.org>',
    senderName: 'Coursera Learning',
    senderEmail: 'learning@coursera.org',
    senderDomain: 'coursera.org',
    to: 'user@example.com',
    subject: 'Reminder: Complete your Machine Learning Specialization certificate',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 750).toISOString(), // > 2 years
    internalDate: Date.now() - 1000 * 60 * 60 * 24 * 750,
    ageDays: 750,
    sizeBytes: 190000,
    sizeFormatted: formatBytes(190000),
    isHeavy5MB: false,
    isHeavy10MB: false,
    isMassNotification: true,
    isAncient1Year: true,
    isAncient2Years: true,
    hasUnsubscribe: true,
    unsubscribeOptions: {
      httpUrl: 'https://coursera.org/account/unsubscribe/edu_901',
      mailto: {
        address: 'unsub@coursera.org',
        subject: 'Unsubscribe',
      },
      rawHeader: '<https://coursera.org/account/unsubscribe/edu_901>, <mailto:unsub@coursera.org>',
    },
    snippet: 'You are only 2 assignments away from finishing Deep Learning Course 4 by Andrew Ng.',
    labels: ['INBOX'],
  },
  {
    id: 'mock-msg-013',
    threadId: 'mock-th-013',
    from: 'Dropbox Storage Team <no-reply@dropbox.com>',
    senderName: 'Dropbox Storage Team',
    senderEmail: 'no-reply@dropbox.com',
    senderDomain: 'dropbox.com',
    to: 'user@example.com',
    subject: 'Your Dropbox space is 94% full - Upgrade now',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 180).toISOString(),
    internalDate: Date.now() - 1000 * 60 * 60 * 24 * 180,
    ageDays: 180,
    sizeBytes: 210000,
    sizeFormatted: formatBytes(210000),
    isHeavy5MB: false,
    isHeavy10MB: false,
    isMassNotification: true,
    isAncient1Year: false,
    isAncient2Years: false,
    hasUnsubscribe: true,
    unsubscribeOptions: {
      httpUrl: 'https://dropbox.com/privacy/unsubscribe?id=dp_3812',
      hasOneClickPost: true,
      rawHeader: '<https://dropbox.com/privacy/unsubscribe?id=dp_3812>',
    },
    snippet: 'You have only 240 MB remaining. Upgrade to Dropbox Plus or delete old shared folders.',
    labels: ['INBOX'],
  },
  {
    id: 'mock-msg-014',
    threadId: 'mock-th-014',
    from: 'Twitter / X Digest <info@x.com>',
    senderName: 'Twitter / X Digest',
    senderEmail: 'info@x.com',
    senderDomain: 'x.com',
    to: 'user@example.com',
    subject: 'Highlights from people you follow: @karpathy, @sama, @ylecun',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 380).toISOString(), // > 1 year
    internalDate: Date.now() - 1000 * 60 * 60 * 24 * 380,
    ageDays: 380,
    sizeBytes: 145000,
    sizeFormatted: formatBytes(145000),
    isHeavy5MB: false,
    isHeavy10MB: false,
    isMassNotification: true,
    isAncient1Year: true,
    isAncient2Years: false,
    hasUnsubscribe: true,
    unsubscribeOptions: {
      httpUrl: 'https://x.com/i/safety/unsub_digest',
      hasOneClickPost: true,
      rawHeader: '<https://x.com/i/safety/unsub_digest>',
    },
    snippet: 'Catch up on top posts discussing modern autonomous coding agents and deep learning transformers.',
    labels: ['INBOX'],
  },
  {
    id: 'mock-msg-015',
    threadId: 'mock-th-015',
    from: 'Zoom Cloud Recordings <no-reply@zoom.us>',
    senderName: 'Zoom Cloud Recordings',
    senderEmail: 'no-reply@zoom.us',
    senderDomain: 'zoom.us',
    to: 'user@example.com',
    subject: 'Cloud Recording - Architecture Sync & Roadmap Q3 (1.2 GB Archive)',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 410).toISOString(), // > 1 year
    internalDate: Date.now() - 1000 * 60 * 60 * 24 * 410,
    ageDays: 410,
    sizeBytes: 18 * 1024 * 1024, // 18 MB email payload with embedded frames
    sizeFormatted: formatBytes(18 * 1024 * 1024),
    isHeavy5MB: true,
    isHeavy10MB: true,
    isMassNotification: true,
    isAncient1Year: true,
    isAncient2Years: false,
    hasUnsubscribe: false,
    snippet: 'Topic: Architecture Sync & Roadmap. Passcode: 881290. Download full resolution mp4 and transcript.',
    labels: ['INBOX'],
  }
];
